export const HELP = {
  settings: {
    autoplay: 'When enabled, the first chapter starts playing automatically when the demo loads.',
    showDuration: 'Global default for showing chapter duration in the sidebar and now-playing bar. Individual chapters can override this.',
    chatEnabled: 'Shows or hides the chat panel on the demo viewer.',
    aiEnabled: 'Enables AI-generated replies to user chat messages when live chat is off or as a fallback.',
    notificationsEnabled: 'Shows browser notifications when new chat messages arrive during a demo session.',
    liveChatEnabled: 'Allows admins to reply to demo chat from the Live Chat page. When on with AI off, only human replies are sent.',
    seedChatEnabled: 'Pre-populates the chat panel with seed messages configured on the Seed Chat page.',
    chapterPickEnabled: 'Lets viewers click chapters in the sidebar. When off, chapter order is controlled by the flow only.',
    pauseEnabled: 'Allows viewers to pause video playback during the demo.',
    aiSystemPrompt: 'System instructions sent to the AI for every chat reply. Describe tone, scope, and product knowledge.',
    themeLogoUrl: 'Logo image URL shown in the demo sidebar header. Upload a file or paste a URL. Replaces brand name text when set.',
    themePrimaryColor: 'Primary accent color used for buttons, highlights, and active states in the demo.',
    themeAccentColor: 'Secondary accent for hover states and emphasis elements.',
    themeBackgroundColor: 'Main background color of the demo viewer shell.',
    themeSurfaceColor: 'Background for sidebars, cards, and elevated surfaces.',
    themeTextColor: 'Default body text color in the demo viewer.',
    themeFontFamily: 'Font family name for the demo (must be loaded or a system font).',
    themeBrandName: 'Text brand name shown in the sidebar when no logo is uploaded.',
    themeChatTitle: 'Heading displayed at the top of the chat panel.',
    slackEnabled: 'Mirror demo chat messages to a Slack channel thread and ingest thread replies back into the demo.',
    slackChannelId: 'Slack channel ID (starts with C) where new demo sessions create a thread. Requires SLACK_BOT_TOKEN env var.',
    teamsEnabled: 'Mirror demo chat to Microsoft Teams via Bot Framework. Requires MICROSOFT_APP_ID and MICROSOFT_APP_PASSWORD env vars.',
    teamsServiceUrl: 'Optional override for the Bot Framework service URL. Usually auto-detected from incoming Teams activities.',
  },
  chapters: {
    name: 'Display name shown in the demo sidebar and chapter list.',
    description: 'Short description of the chapter content (used in admin; not always shown in demo).',
    videoLink: 'YouTube video ID or full URL, or a direct MP4 URL. Parsed automatically at playback time.',
    duration: 'Display duration string (e.g. 12:34). Shown when duration visibility is enabled.',
    showDuration: 'Override global duration visibility for this chapter. Global uses the Settings toggle.',
    locked: 'When locked, viewers must complete a gate form before watching this chapter.',
  },
  flows: {
    enabled: 'Disabled flows are hidden from public URLs. The flow editor remains accessible from admin.',
  },
  events: {
    title: 'Display name for the scheduled event shown in the lobby and admin list.',
    slug: 'URL-safe identifier used at /event/{slug}. Lowercase letters, numbers, and hyphens only.',
    flow: 'Demo flow played when the event goes live. Required — create a flow first if the list is empty.',
    enabled: 'Disabled events return 404 on public URLs and are skipped in scheduling.',
    recurrence: 'One-time fires once at Starts at. Interval repeats every N minutes. Weekly uses selected days and times.',
    startsAt: 'Local date/time when a one-time event goes live. Converted to UTC on save.',
    intervalMinutes: 'Minutes between each occurrence when using interval recurrence.',
    anchorStart: 'UTC anchor datetime for interval recurrence calculations.',
    weeklyDays: 'Days of the week when a weekly recurring event can go live.',
    weeklyTimes: 'Local times (HH:mm) on selected days when the event goes live.',
    timezone: 'IANA timezone for weekly schedule times (e.g. America/New_York).',
    seriesEnd: 'Optional end datetime after which no further occurrences are scheduled.',
    liveDurationMinutes: 'How long the event stays in the live state after each start time.',
    holdingHeading: 'Heading shown on the event lobby page before the broadcast goes live.',
    holdingMessage: 'Body text on the lobby waiting screen.',
    holdingImageUrl: 'Hero image URL for the lobby page (shown above or beside the holding video).',
    holdingVideoUrl: 'YouTube ID/URL or direct MP4 shown on the lobby while waiting. Leave empty for no video.',
    defaultChapter: 'Chapter played first when the event goes live and the viewer enters the demo.',
  },
  toasters: {
    type: 'Popup overlays the video. Banner shows top/bottom strip. Download prompts a file. Graphic is a clickable image card.',
    chapter: 'Chapter where this toaster appears. Leave as Global to show on any chapter at the trigger time.',
    triggerAtSeconds: 'Seconds into chapter playback when the toaster appears.',
    durationSeconds: 'Auto-dismiss after this many seconds. Set 0 to require manual dismiss.',
    title: 'Headline text inside the toaster.',
    message: 'Body text or description shown in the toaster.',
    enabled: 'Disabled toasters are not shown during demo playback.',
    imageUrl: 'Image displayed inside popup, banner, or graphic toasters.',
    linkUrl: 'URL opened when the viewer clicks a graphic toaster.',
    linkNewWindow: 'Opens the graphic link in a new browser tab instead of the same window.',
    bannerPosition: 'Whether the banner strip appears at the top or bottom of the video area.',
    thumbnailUrl: 'Preview thumbnail shown on download toasters.',
    downloadUrl: 'File URL the viewer downloads when clicking the download toaster.',
    downloadFileName: 'Suggested filename for the downloaded file.',
  },
  pause: {
    chapter: 'Chapter where playback pauses. Global applies to any chapter at the trigger time.',
    triggerAtSeconds: 'Seconds into playback when the video pauses and the prompt appears.',
    prompt: 'Question or instruction shown to the viewer while paused.',
    fieldId: 'Unique ID stored with the answer. Branch nodes can route based on this field ID.',
    inputType: 'Control type for the answer: text, multiline, radio, multi-select, date, email, etc.',
    options: 'Comma-separated choices for radio or multi-select inputs.',
    required: 'Viewer must answer before continuing playback.',
    enabled: 'Disabled pause points are skipped during playback.',
  },
  seedChat: {
    role: 'Assistant messages appear as bot replies. User messages appear as if sent by a visitor.',
    text: 'Message content shown in the chat panel when seed chat is enabled in Settings.',
  },
  liveChat: {
    reply: 'Reply sent to the active demo session. Appears in the viewer chat and external integrations (Slack/Teams) if enabled.',
  },
  flowEditor: {
    projectName: 'Internal name for this flow project. Shown in the admin flow list.',
    nodeName: 'Label for this node on the flow canvas. Does not affect demo viewer text unless mapped to a parameter.',
    introHeading: 'Main heading on the intro screen before playback starts.',
    introSubtext: 'Supporting text below the intro heading.',
    questionFieldId: 'Unique ID for this answer. Must match branch node source fields for routing.',
    questionLabel: 'Prompt text shown to the viewer.',
    questionInputType: 'Input control type for collecting the answer.',
    questionOptions: 'Choices for radio or multi-select questions, one per line.',
    questionPlaceholder: 'Hint text inside empty input fields.',
    questionRequired: 'Viewer must answer before continuing the flow.',
    eventSource: 'Inline creates a countdown from fields below. Slug links to a scheduled event from the Events page.',
    eventSlug: 'Slug of an existing scheduled event (see Events admin).',
    eventTitle: 'Title shown on the inline event countdown screen.',
    eventStartsAt: 'UTC ISO datetime when the inline countdown ends and playback begins.',
    eventHeading: 'Heading on the inline holding screen.',
    eventMessage: 'Message on the inline holding screen.',
    eventImageUrl: 'Hero image for the inline holding screen.',
    eventVideoType: 'Type of preview video on the holding screen: none, YouTube, or direct MP4.',
    eventVideoUrl: 'YouTube ID/URL or direct MP4 URL for the holding screen preview.',
    eventDefaultChapter: 'Chapter to play when the inline countdown completes.',
    branchSourceField: 'Field ID from a previous question whose answer is matched by branch rules.',
    branchMatch: 'Value to compare against the source field answer (exact match).',
    branchAction: 'Go to node continues the flow. Open URL sends the viewer to an external page.',
    branchTarget: 'Target flow node ID when action is Go to node.',
    branchUrl: 'External URL opened when action is Open URL.',
    branchDefaultUrl: 'Fallback URL when no branch rule matches the answer.',
    aichatHeading: 'Title shown on the AI chat interaction panel.',
    aichatDuration: 'How long (seconds) the AI chat panel stays open during playback.',
    aichatInteractionCount: 'Maximum number of chat exchanges during this node.',
    aichatPromptMode: 'Fixed uses the prompt list in order. Random picks from the random pool.',
    aichatPrompts: 'Suggested prompts shown to the viewer, one per line.',
    aichatRandomPool: 'Pool of prompts for random mode, one per line.',
    aichatUseAiReply: 'Allows the viewer to send their own messages and receive AI replies during this segment.',
    chapterSelect: 'Links this node to a chapter record. Video content comes from the Chapters table.',
    chapterName: 'Chapter display name synced to the shared Chapters database.',
    chapterDescription: 'Chapter description synced to the shared Chapters database.',
    chapterVideoLink: 'YouTube ID/URL or MP4 URL for this chapter. Saved to the Chapters table.',
    chapterDuration: 'Display duration string (e.g. 12:34) saved to the chapter record.',
    chapterShowDuration: 'Override global duration visibility for this chapter.',
    chapterLocked: 'Requires gate form completion before this chapter can be watched.',
    toasterTriggerAt: 'Seconds into chapter playback when the toaster fires.',
    toasterDuration: 'Auto-dismiss seconds. 0 means the viewer must close it manually.',
    toasterType: 'Visual style: popup overlay, banner strip, download prompt, or clickable graphic.',
    toasterTitle: 'Headline inside the toaster.',
    toasterMessage: 'Body text in the toaster.',
    toasterImageUrl: 'Image URL for popup, banner, or graphic toasters.',
    toasterLinkUrl: 'Click destination for graphic toasters.',
    toasterLinkNewWindow: 'Open graphic link in a new tab.',
    toasterBannerPosition: 'Top or bottom placement for banner toasters.',
    toasterThumbnailUrl: 'Thumbnail on download toasters.',
    toasterDownloadUrl: 'File URL for download toasters.',
    toasterDownloadFileName: 'Suggested download filename.',
    pauseTriggerAt: 'Video pause timestamp in seconds from chapter start.',
    pausePrompt: 'Question shown while the video is paused.',
    pauseFieldId: 'Answer storage ID. Use in branch nodes for conditional routing.',
    pauseInputType: 'Input control for the paused question.',
    pauseOptions: 'Comma-separated options for radio or multi-select.',
    pauseRequired: 'Viewer must answer before playback resumes.',
    pausePlaceholder: 'Placeholder hint inside the input field.',
  },
} as const
